config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "boards#index"

  resources :boards do 
    resources :lists
  end

  resources :lists do 
    resources :tasks
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :lists, dependent: :destroy

  def self.all_boards(user_id)
    Board.find_by_sql(
      "SELECT *
      FROM boards AS b
      WHERE b.user_id = #{user_id}"
    )
  end
    
  def self.single_board(user_id, board_id)
    Board.find_by_sql(["
      SELECT * 
      FROM boards AS b
      WHERE b.id = ? AND b.user_id = ?
    ", board_id, user_id]).first
  end
  
  def self.create_board(p, id)
    Board.find_by_sql(["
      INSERT INTO boards (name, :user_id, :created_at, :updated_at);
    ", {
      first: p[:name],
      user_id: id,
      created_at: DateTime.now,
      updated_at: DateTime.now
    }])
  end
  
  def self.update_board(board_id, p)
    Board.find_by_sql(["
      UPDATE boards AS c
      SET name = ?, updated_at = ?
      WHERE b.id = ?
    ;", p[:name], DateTime.now, board_id])
  end
  
  def self.delete_board(board_id)
    Board.find_by_sql(["
      DELETE FROM boards AS b
      WHERE b.id = ?
    ;", board_id])
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  def full_name
    "#{self.first_name} #{self.last_name}"
  end  
  
  has_many :lists, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only [:show, :edit, :update, :destroy]
  
  #SELECT all records that belong to User
  def index
    @boards = Board.all_boards(current_user.id)
  end

  def new
    @board = current_user.boards.new
  end

  def show
  end

  def create
    # INSERT one record
    Board.create_board(board_params, current_user[:id])
    redirect_to boards_path
  end

  def edit
  end

  def update
  Board.update_board(@board.id, board_params)
  end

  def destroy
    board.delete_board(@board.id)
    redirect_to boards_path
end

  private

  def set_board
    #SELECT single record
    @board = Board.single_board(current_user.id, params[:id])
  end

  def board_params
    params.require(:board).permit(:name)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board

  def index
    @specialized = @board.lists.where(role: 'specialist')
    @advanced = @board.lists.where(role: 'advanced')
    @anyone = @board.lists.where(role: 'anyone')
  end

  def new
    @list = @board.lists.new
  end

  def create
    @list = @board.lists.new(list_params)
    if @listt.save
      redirect_to board_lists_path(@board)
    else
      render :new
    end
  end

  def destroy
    @list = @board.lists.find(params[:id])
    @list.destroy
    redirect_to board_lists_path(@board)
  end

 private
   def set_board
     @board = board.find(params[:board_id]) 
   end

   def list_params
     params.require(:list).permit(:role, :user_id)
   end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @users = User.all - @board.users
    @task = @board.lists.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: @board, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "input" %>
  </div>
 
 <%= f.submit nil, class: "ui blue button" %>
<% end %>

app/views/boards/edit.html.erb
<h1>Edit Board</h1>

<%= render "form" %>

app/views/boards/index.html.erb
<h1>Boards</h1>

<% @boards.each do |board| %>
  <div>
    <h3><%= link_to board.name, board %></h3>
  </div>
<% end %>

app/views/boards/new.html.erb
<h1>Add Board</h1>

<%= render "form" %>

app/views/boards/show.html.erb
<h1><%= @board.name %></h1>

<%= link_to "Edit", edit_board_path(@board), class: "ui orange button" %>
<%= link_to "Delete", @board, method: :delete, class: "ui red button" %>

app/views/layouts/_navbar.html.erb
<nav class="ui menu">
  <%= link_to "Boards", boards_path, class: "item" %>
  <%= link_to "Add Board", new_board_path, class: "item" %>
  <div class="right menu">
    <% if current_user %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "item" %>
    <% else %>
      <%= link_to "Register", new_user_registration_path, class: "item" %>
      <%= link_to "Login", new_user_session_path, class: "item" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trollo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
      <%= render "layouts/navbar" %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Listss</h1>
<%= link_to 'Add List', new_board_list_path %>
<hr />
<h2><%= @lists.length <= 0 ? "No List" : "" %></h2> 
<ul>
  <% @lists.each do |list| %>
    <li>
      <%= link_to list.name, list %>
    </li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<h1>Add List</h1>
<%= form_with(model: @list, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "List Name" %>
  </div>
  <%= f.submit nil, class: "ui blue button" %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @board.name %></h1>
<hr />
<br />
<%= link_to 'Lists', board_lits_path(@board), class: "ui primary button inverted" %>
<br />
<br />
<br />
<%= link_to "Delete List", @board, method: :delete, class: "ui red button inverted" %>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<h1><%= @board.name %>: lists</h1>
<%= link_to 'Add List', new_board_list_path(@board) %>
<hr />

<h2>Specialized</h2>
<ul>
  <% @Specializeds.each do |specialized| %>
    <li>
      <%= specialized.user.full_name %>
      <br />
      <%= link_to 'Remove', board_list_path(@board, specialized), method: :delete %>
    </li>
  <% end %>
</ul>
<h2>Advanced</h2>
<ul>
  <% @Advanceds.each do |advanced| %>
    <li>
      <%= advanced.user.full_name %>
      <br />
      <%= link_to 'Remove', board_list_path(@board, advanced), method: :delete %>
    </li>
 <% end %>
</ul>
<h2>Anyone</h2>
<ul>
  <% @anyones.each do |anyone| %>
    <li>
      <%= anyone.user.full_name %>
      <br />
      <%= link_to 'Remove', course_enrollment_path(@course, anyone), method: :delete %>
   </li>
 <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Add Task</h1>
<%= form_with(model: [@board, @list], local: true, class: "ui form" ) do |f| %>
  <%= f.label :user %>
  <%= f.select :user_id, @users.collect { |u| [u.full_name, u.id] } %>
  <br />
  <%= f.label :role %>
  <%= f.select :role, ['Advanced', 'Specialized', 'Anyone'] %>
  <br />
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

app/views/users/index.html.erb
<h1>Users</h1>
<%= link_to 'Add User', new_user_path %>
<hr />
<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.full_name, user %>
    </li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Add User</h1>
<%= form_with(model: @user, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, autofocus: true, placeholder: "First Name" %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
  </div>
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>
<hr />
<h2>Lists</h2>
<ul>
  <% @user.lists.each do |list| %>
    <li>
      <%= link_to list.name, list %>
    </li>
  <% end %>
</ul>
<br />
<br />
<br />
<%= link_to 'Delete User', @user, method: :delete, class: "ui red button inverted" %>
 